#Sai Sandeep Varma Mudundi, G01352322, smudund@gmu.edu
#Team Details
# Sai Anjaneya Sowrab Meduri( G01270421)
# Rajeev Priyatam Panchadula( G01333080)
# Lakshmi Guttikonda(G01334433)
#defines how the built container should be deployed on Kubernetes. 
#The definition pulls the built container from Docker Hub and creates a new deployment with it in your Kubernetes cluster. 
#It also creates a LoadBalancer service so that the deployment can be accessed from outside the cluster.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: surveyapp
  labels:
    app: surveyapp
spec:
  replicas: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: surveyapp
      
  template:
    metadata:
      labels:
        app: surveyapp
        tier: surveyapp
    spec:
      containers:
        - name: surveyapp
          image: sandeepvarma99/hw2surveyapp:1.0
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
            name: surveyapp


---
apiVersion: v1
kind: Service
metadata:
  name: surveyapp
  labels:
    app: surveyapp
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: surveyapp
    tier: surveyapp
  type: LoadBalancer
